# Generated by Django 5.2.11 on 2026-02-17 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='e.g. signal_received, order_created', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context as JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker_name', models.CharField(help_text='e.g. MetaTrader5, cTrader', max_length=100)),
                ('account_id', models.CharField(help_text='Broker account identifier', max_length=100)),
                ('encrypted_api_key', models.TextField(help_text='Fernet-encrypted broker API key')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('instrument', models.CharField(help_text='e.g. EURUSD, XAUUSD', max_length=20)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=5, help_text='None means executed at market price', max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('fake_order_id', models.CharField(blank=True, help_text='Simulated order ID returned by the mock broker', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='signals_app.brokeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
